{"name": "Проверяем код и текст ответа при создании двух курьеров с одинаковым набором данных", "status": "failed", "statusDetails": {"message": "AssertionError: assert (409 == 409 and 'Этот логин уже используется' == 'Этот логин у...буйте другой.'\n +  where 409 = <Response [409]>.status_code\n  \n  - Этот логин уже используется. Попробуйте другой.\n  + Этот логин уже используется)", "trace": "@allure.title('Проверяем код и текст ответа при создании двух курьеров с одинаковым набором данных')\n    def test_create_clone_courier():\n        courier_data = RegisterNewCourier.random_courier()\n        response = requests.post(f\"{Urls.BASE_URL}{Urls.CREATE}\", data=courier_data)\n        response_second = requests.post(f\"{Urls.BASE_URL}{Urls.CREATE}\", data=courier_data)\n>       assert 409 == response_second.status_code and RegistrationAnswers.server_answer_code_409 == response_second.json()[\"message\"]\nE       AssertionError: assert (409 == 409 and 'Этот логин уже используется' == 'Этот логин у...буйте другой.'\nE        +  where 409 = <Response [409]>.status_code\nE         \nE         - Этот логин уже используется. Попробуйте другой.\nE         + Этот логин уже используется)\n\ntests\\test_create_courier.py:18: AssertionError"}, "start": 1727113585291, "stop": 1727113585637, "uuid": "6e9067ba-a5f7-451f-9408-a565f869517e", "historyId": "4a3d86fc44b823d5c4809334804e6ff9", "testCaseId": "4a3d86fc44b823d5c4809334804e6ff9", "fullName": "tests.test_create_courier#test_create_clone_courier", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "host", "value": "Yandex-Team"}, {"name": "thread", "value": "1880-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}